USE DB_PIM_HOTEL
GO 

IF EXISTS (SELECT * FROM SYS.procedures WHERE NAME = 'PR_INSERT_FUNCIONARIO')
	DROP PROCEDURE PR_INSERT_FUNCIONARIO
GO 

CREATE PROCEDURE PR_INSERT_FUNCIONARIO 
	@V_NOME_FUNCIONARIO			VARCHAR(100) = NULL, 
	@SOBRENOME_FUNCIONARIO		VARCHAR(100) = NULL,
	@V_CPF_FUNCIONARIO			VARCHAR(11)	 = NULL, 
	@V_RG_FUNCIONARIO			VARCHAR(11)	 = NULL,
	@V_SEXO_FUNCIONARIO			CHAR(1)		 = NULL,
	@V_PAIS_FUNCIONARIO			VARCHAR(20)	 = NULL,
	@V_CIDADE_FUNCIONARIO		VARCHAR(30)	 = NULL,
	@V_RUA_FUNCIONARIO			VARCHAR(50)	 = NULL,
	@V_DT_NASC_FUNCIONARIO		DATE		 = NULL,
	@V_CEP_FUNCIONARIO			VARCHAR(8)	 = NULL,
	@V_TELEFONE_FUNCIONARIO		VARCHAR(11)	 = NULL,
	@V_LOGIN_FUNCIONARIO		VARCHAR(50)	 = NULL,  
	@V_SENHA_FUNCIONARIO		VARCHAR(50)	 = NULL
AS
BEGIN 

	-- VERIFICA SE FUNCIONARIO EXISTE

	IF EXISTS (SELECT 1 FROM TB001_FUNCIONARIO WHERE CPF_FUNCIONARIO = @V_CPF_FUNCIONARIO)
		PRINT 'FUNCIONARIO JÁ CADASTRADO, POR FAVOR FAZER ATUALIZAÇÃO'
	ELSE 
	
	BEGIN TRY 

		INSERT INTO TB001_FUNCIONARIO
           (
				NOME_FUNCIONARIO
			   ,SOBRENOME_FUNCIONARIO
			   ,CPF_FUNCIONARIO
			   ,RG_FUNCIONARIO
			   ,SEXO_FUNCIONARIO
			   ,PAIS_FUNCIONARIO
			   ,CIDADE_FUNCIONARIO
			   ,RUA_FUNCIONARIO
			   ,DT_NASC_FUNCIONARIO
			   ,CEP_FUNCIONARIO
			   ,TELEFONE_FUNCIONARIO
			   ,LOGIN_FUNCIONARIO
			   ,SENHA_FUNCIONARIO
		   )
     VALUES
           (
				@V_NOME_FUNCIONARIO		,		 
				@SOBRENOME_FUNCIONARIO	,	
				@V_CPF_FUNCIONARIO		,		
				@V_RG_FUNCIONARIO		,		
				@V_SEXO_FUNCIONARIO		,	
				@V_PAIS_FUNCIONARIO		,	
				@V_CIDADE_FUNCIONARIO	,	
				@V_RUA_FUNCIONARIO		,	
				@V_DT_NASC_FUNCIONARIO	,
				@V_CEP_FUNCIONARIO		,
				@V_TELEFONE_FUNCIONARIO	,
				@V_LOGIN_FUNCIONARIO	,
				@V_SENHA_FUNCIONARIO
			)

			PRINT 'DADOS GRAVADOS COM SUCESSO!'

		END TRY 

		BEGIN CATCH
			PRINT 'UM OU MAIS CAMPOS NÃO FORAM PREENCHIDOS DEVIDAMENTE. VALOR NÃO INCLUÍDO.'
		END CATCH
END

GO

CREATE PROCEDURE PR_CONSULTA_FUNCIONARIO 
	@V_CPF_FUNCIONARIO			VARCHAR(11)	 = NULL
AS
BEGIN 
	
	IF @V_CPF_FUNCIONARIO = NULL


END





